=== SebaZ-jpg/Clase_Lenguaje_de_Marcas/ejercicio_final/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cursos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso" max0ccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Titulo" type="xs.string"/>
                            <xs:element name="nivel" type="xs.string"/>
                            <xs:element name="horas" type="xs.integer"/>
                            <xs:element name="categorias" type="xs.string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

=== SebaZ-jpg/Clase_Lenguaje_de_Marcas/ejercicio_final/data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<cursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="data.xsd">

    <curso id="c1">
        <Titulo> HTML Y CSS </Titulo>
        <nivel>Principiante</nivel>
        <horas>50</horas>
        <categoria>Frontend</categoria>
    </curso>

    
    <curso id="c2">
        <Titulo> Javacript para web </Titulo>
        <nivel>Intermedio</nivel>
        <horas>80</horas>
        <categoria>Frontend</categoria>
    </curso>

    
    <curso id="c3">
        <Titulo> Base de datos </Titulo>
        <nivel>Intermedio</nivel>
        <horas>40</horas>
        <categoria>Backend</categoria>
    </curso>

    
    <curso id="c4">
        <Titulo> Programacion en Java </Titulo>
        <nivel>Intermedio</nivel>
        <horas>50</horas>
        <categoria>Backend</categoria>
    </curso>
</cursos>
